version: 2

# Configuration for Percy project
project:
  token: web_ce32d87d4fbb59aa73d7418e720ace6cddd034400c507a676f7b10ad6c40719b
  name: Visual regression Test
#Set Variables
env:
PERCY_TARGET_BRANCH: main 
# Configuration for snapshots
snapshot:
  # Include any global widths or breakpoints for your snapshots
  widths:
    - 375  # Example: mobile
    # - 768  # Example: tablet
    - 1440 # Example: desktop

# Define which files to ignore during visual tests
ignore:
  # Files or directories to ignore
  - node_modules/
  - .git/
  - .DS_Store

# Define which directories should be uploaded to Percy
upload:
  # Directories to upload
  - public/
  - build/

# Choose your Percy agent and version (if applicable)
agent:
  name: percy-cypress
  version: 4.0.0  # Specify the desired agent version

# Set up additional Percy features (optional)
# notifications:
#   slack:
#     # Configure Slack notifications
#     webhook_url: https://hooks.slack.com/services/your-webhook-url

# Concurrent test execution configuration
concurrency:
  # Maximum number of parallel test runs
  max: 10
  # Minimum number of parallel test runs
  min: 2

# Approvals configuration (optional)
approvals:
  # Threshold for visual changes (0-100)
  threshold: 1

# Configuration for base branch diff (optional)
baseBranch: main



